export const SET_HIGHLINES = "SET_HIGHLINES";
export const NOT_HIGHLINES = "NOT_HIGHLINES";
export const FETCH_HIGHLINES_FAILED = "FETCH_HIGHLINES_FAILED";
export const RESET_HIGHLINE = "RESET_HIGHLINE";

export const FILTER_HIGHLINE = "FILTER_HIGHLINE";
export const SET_HIGHLINE = "SET_HIGHLINE";
export const SET_HIGHLINE_ID = "SET_HIGHLINE_ID";
export const POST_HIGHLINE_FAILED = "POST_HIGHLINE_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_LOCATION_NAME = "FETCH_LOCATION_NAME";
export const SET_LOCATION = "SET_LOCATION";
export const CLEAR_LOCATION = "CLEAR_LOCATION";
export const POST_LOCATION_FAILED = "POST_LOCATION_FAILED";
export const SET_LOCATION_ID = "SET_LOCATION_ID";

export const SET_RANDOM_IMAGE = "SET_RANDOM_IMAGE";
export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const ON_SEARCH = "ON_SEARCH";
export const SET_REDIRECT = "SET_REDIRECT";

export const CLEAN_MESSAGE = "CLEAN_MESSAGE"
